const express = require("express");
const router = express.Router();
const AuthRoutes = require("./authRoute");
const FileRoutes = require("./fileRoute");
const VideoRoutes = require("./VideoRoute");
const TemplateRoutes = require("./templateRoute");
router.use("/auth", AuthRoutes);
router.use("/file", FileRoutes);
router.use("/video", VideoRoutes);
router.use("/template", TemplateRoutes);
module.exports = router;
