const express = require("express");
const router = express.Router();
const AuthRoutes = require("./authRoute");
const FileRoutes = require("./fileRoute");
const VideoRoutes = require("./VideoRoute");
const StorageRoutes = require("./storageRoute");
router.use("/auth", AuthRoutes);
router.use("/file", FileRoutes);
router.use("/video", VideoRoutes);
router.use("/storage", StorageRoutes);
module.exports = router;
